// Write a nodejs program load a simple html file on nodejs web server and print
// its content as html content. (By requesting url from browser)var h = require('http')
var h = require('http')
var fs = require('fs')
var url = require('url')
var server = h.createServer(function (req, res) {
  var q = url.parse(req.url, true)
  //   data = fs.readFileSync('.' + q.pathname)
  data = fs.readFileSync('EX1&2.html')
  res.writeHead(200, { 'content-type': 'text/html' })
  res.write(data)
  console.log(data)
  res.write('<h1> hello</h1>')
  res.end()
})
server.listen(6055)
